export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";

export const FETCH_PRODUCT_FAILED = "FETCH_PRODUCT_FAILED";

export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";

export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";
